### ISSUE TITLE
innogy adapter running into an error and restarting

### ISSUE THREAD

**Issue by GreatSUN** [PArns/ioBroker.innogy-smarthome#108]
**Describe the bug**  
Adapter running into errors and restarting

**To Reproduce**  
No idea...

**Expected behavior**  
It does either not run into the error or successfully catches it and reports the issue in the log.

**Screenshots & Logfiles**  
innogy-smarthome.0 | 2023-03-28 09:40:50.834 | debug | SOCKET CONNECTION TO THE INNOGY API WAS CLOSED
-- | -- | -- | --
innogy-smarthome.0 | 2023-03-28 09:40:50.829 | debug | STACK: RangeError: Invalid WebSocket frame: invalid status code 0 at Receiver.controlMessage (/opt/iobroker/node_modules/ws/lib/receiver.js:566:18) at Receiver.getData (/opt/iobroker/node_modules/ws/lib/receiver.js:442:42) at Receiver.startLoop (/opt/iobroker/node_modules/ws/lib/receiver.js:158:22) at Receiver._write (/opt/iobroker/node_modules/ws/lib/receiver.js:84:10) at writeOrBuffer (node:internal/streams/writable:391:12) at _write (node:internal/streams/writable:332:10) at Receiver.Writable.write (node:internal/streams/writable:336:10) at Socket.socketOnData (/opt/iobroker/node_modules/ws/lib/websocket.js:1278:35) at Socket.emit (node:events:513:28) at Socket.emit (node:domain:489:12) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:289:9) at Socket.Readable.push (node:internal/streams/readable:228:10) at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
innogy-smarthome.0 | 2023-03-28 09:40:50.828 | debug | GOT AN IGNORED ERROR: {"code":"WS_ERR_INVALID_CLOSE_CODE"}
innogy-smarthome.0 | 2023-03-28 09:40:50.683 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
innogy-smarthome.0 | 2023-03-28 09:40:50.683 | debug | Plugin sentry destroyed
innogy-smarthome.0 | 2023-03-28 09:40:50.682 | info | terminating
innogy-smarthome.0 | 2023-03-28 09:40:50.682 | info | cleaned everything up...
innogy-smarthome.0 | 2023-03-28 09:40:50.681 | debug | SOCKET CONNECTION TO THE INNOGY API WAS CLOSED
innogy-smarthome.0 | 2023-03-28 09:40:50.659 | error | 400 - {"errorcode":1005,"description":"Missing argument or wrong value","messages":["Invalid action: unresolved reference to [/device/2271105d6c7f46ee97dafda67f384dd6] in entity [/capability/000cb08a9def47d181088ec2780f8958]"]}
innogy-smarthome.0 | 2023-03-28 09:40:50.658 | error | StatusCodeError: 400 - {"errorcode":1005,"description":"Missing argument or wrong value","messages":["Invalid action: unresolved reference to [/device/2271105d6c7f46ee97dafda67f384dd6] in entity [/capability/000cb08a9def47d181088ec2780f8958]"]} at new StatusCodeError (/opt/iobroker/node_modules/request-promise-core/lib/errors.js:32:15) at Request.plumbing.callback (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:104:33) at Request.RP$callback [as _callback] (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:46:31) at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22) at Request.emit (node:events:513:28) at Request.emit (node:domain:489:12) at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1154:10) at Request.emit (node:events:513:28) at Request.emit (node:domain:489:12) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1076:12) at Object.onceWrapper (node:events:627:28) at IncomingMessage.emit (node:events:525:35) at IncomingMessage.emit (node:domain:489:12) at endReadableNT (node:internal/streams/readable:1358:12) at processTicksAndRejections (node:internal/process/task_queues:83:21)
innogy-smarthome.0 | 2023-03-28 09:40:50.658 | error | unhandled promise rejection: 400 - {"errorcode":1005,"description":"Missing argument or wrong value","messages":["Invalid action: unresolved reference to [/device/2271105d6c7f46ee97dafda67f384dd6] in entity [/capability/000cb08a9def47d181088ec2780f8958]"]}
innogy-smarthome.0 | 2023-03-28 09:40:50.657 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
innogy-smarthome.0 | 2023-03-28 09:40:50.243 | debug | Setting capability 000cb08a9def47d181088ec2780f8958/PointTemperature to 6.5

**Versions:**  
 - Adapter version: v1.2.6
 - JS-Controller version: 4.0.24
 - Node version: v16.19.1
 - Operating system: debian 11.6

**Additional context**  
If I can support you in any way, please don't hesitate to come through.

**Comment by GreatSUN** [comment]
Guess it's an hardware issue with the livisi central.
