### ISSUE TITLE
Fehlermeldungen

### ISSUE THREAD

**Issue by facecreator** [PArns/ioBroker.innogy-smarthome#22]
Hallo, 
Ich habe leider immer wieder Fehlermeldungen im LOG. 

2018-09-26 05:57:03.392  - error: Caught by controller[0]: TypeError: Cannot read property 'needsAuthorization' of undefined
2018-09-26 05:57:03.394  - error: Caught by controller[0]:     at /opt/iobroker/node_modules/innogy-smarthome-lib/lib/requestor/index.js:50:24
2018-09-26 05:57:03.394  - error: Caught by controller[0]:     at /opt/iobroker/node_modules/innogy-smarthome-lib/lib/oauth2/index.js:274:25
2018-09-26 05:57:03.395  - error: Caught by controller[0]:     at /opt/iobroker/node_modules/innogy-smarthome-lib/lib/oauth2/index.js:237:29
2018-09-26 05:57:03.396  - error: Caught by controller[0]:     at /opt/iobroker/node_modules/graceful-fs/graceful-fs.js:99:16
2018-09-26 05:57:03.396  - error: Caught by controller[0]:     at /opt/iobroker/node_modules/graceful-fs/graceful-fs.js:43:10
2018-09-26 05:57:03.397  - error: Caught by controller[0]:     at FSReqWrap.oncomplete (fs.js:135:15)
2018-09-26 05:57:03.397  - error: host.orangepiplus2e instance system.adapter.innogy-smarthome.0 terminated with code 0 (OK)

Waere gut wenn sich das mal jemand ansehen koennte.

**Comment by PArns** [comment]
Das Problem sollte bereits behoben sein, kannst du das mit der aktuellen Version immer noch nachvollziehen?
