### ISSUE TITLE
Funktion "WindowReductionActive" funktioniert nicht mehr

### ISSUE THREAD

**Issue by rassel2000** [PArns/ioBroker.innogy-smarthome#82]
Hallo,

ich nutze die oben genannte Funktion, um bei meinen HKTs die Absenkung zu aktivieren (ausgelöst durch Aqara Fensterkontakte).
Bis vor ein paar Tagen wurde die Absenkung durch die HKTs ohne Probleme durchgeführt. Seit kurzem bekomme ich aber nur noch Fehlermeldungen und die HKTs verbleiben in ihrem aktuellen Modus, egal ob ich das lokale SmartHome oder die Cloudverbindung nutze.
Im Log steht der Fehler "STATE ERR {"error":"CAPABILITY NOT FOUND!"}.
Ich hatte bisher die Adapterversion 0.4.5 installiert, ein Update auf 0.4.7 hat aber leider nichts gebracht.

Node.js: v16.16.0
js-controller: v4.0.23

Ich habe die böse Vermutung, dass Livisi irgendwas an der Firmware der Zentrale geändert hat.

Könntest du dir das mal angucken?

Danke!

**Comment by haahne** [comment]
Nabend,
Ich wollte bei mir auch die Aqara Sensoren als Trigger nehmen. Wenn ich den Wert "WindowReductionActive" auf true setze passiert nichts. Die Thermostate behalten Ihre Eingestellte Temperatur bei.
Hab es mit 0.3.7 und mit 0.4.7 Probiert, bei beide Funktioniert es nicht. 

Grüße

**Comment by Apollon77** [comment]
Does the log state anything?

**Comment by haahne** [comment]
Da ich mit der 0.4.7 nicht testen kann weil ich keine Verbindung aufbauen kann, kann ich nur sagen was er bei der 0.3.7 sagt.
Da sagt er unter Debug " Open" 
Mehr nicht. Nach ein paar Sekunden springt der State wieder auf False zurück.

**Comment by Apollon77** [comment]
Ok, ich bereite ein größeres Update vor, mit dem könnte man nochmal testen. Es ändert sich aber die Objektstruktur - es kommt eine Ebene dazu die fehlte! Die GitHub version wäre testbar und geht auch mit SHC1 im lokalen Modus - einfach SHC Generation in der Konfig auswählen

**Comment by Apollon77** [comment]
see https://forum.iobroker.net/topic/61351/livisi-innogy-smarthome-adapter-1-0-0-breaking ... How it is with this version=ß Please provide a log

**Comment by haahne** [comment]
Wenn ich den State ändere schmiert der ganze Adapter ab:

<html>
<body>


2022-12-25 10:52:06.641 - debug: innogy-smarthome.0 (1817) Setting capability b716e897306b41f4b433ab60041f5563/WindowReductionActive to true
--
2022-12-25 10:52:06.693 - error: innogy-smarthome.0 (1817) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-12-25 10:52:06.694 - error: innogy-smarthome.0 (1817) unhandled promise rejection: 400 - {"errorcode":1005,"description":"Missing argument or wrong value","messages":["Parameter [ windowReductionActive ] does not exist. Err: [ parameter [windowReductionActive] not found in action [SetState] ]"]}
2022-12-25 10:52:06.695 - error: innogy-smarthome.0 (1817) StatusCodeError: 400 - {"errorcode":1005,"description":"Missing argument or wrong value","messages":["Parameter [ windowReductionActive ] does not exist. Err: [ parameter [windowReductionActive] not found in action [SetState] ]"]}
at new StatusCodeError (/opt/iobroker/node_modules/request-promise-core/lib/errors.js:32:15)
at Request.plumbing.callback (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:104:33)
at Request.RP$callback [as _callback] (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:46:31)
at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
at Request.emit (node:events:513:28)
at Request. (/opt/iobroker/node_modules/request/request.js:1154:10)
at Request.emit (node:events:513:28)
at IncomingMessage. (/opt/iobroker/node_modules/request/request.js:1076:12)
at Object.onceWrapper (node:events:627:28)
at IncomingMessage.emit (node:events:525:35)
at endReadableNT (node:internal/streams/readable:1358:12)
at processTicksAndRejections (node:internal/process/task_queues:83:21)
2022-12-25 10:52:06.695 - error: innogy-smarthome.0 (1817) 400 - {"errorcode":1005,"description":"Missing argument or wrong value","messages":["Parameter [ windowReductionActive ] does not exist. Err: [ parameter [windowReductionActive] not found in action [SetState] ]"]}
2022-12-25 10:52:06.702 - debug: innogy-smarthome.0 (1817) SOCKET CONNECTION TO THE INNOGY API WAS CLOSED
2022-12-25 10:52:06.703 - info: innogy-smarthome.0 (1817) cleaned everything up...
2022-12-25 10:52:06.704 - info: innogy-smarthome.0 (1817) terminating
2022-12-25 10:52:06.705 - warn: innogy-smarthome.0 (1817) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-12-25 10:52:06.710 - debug: innogy-smarthome.0 (1817) GOT AN IGNORED ERROR: {"code":"WS_ERR_INVALID_CLOSE_CODE"}
2022-12-25 10:52:06.711 - debug: innogy-smarthome.0 (1817) STACK: RangeError: Invalid WebSocket frame: invalid status code 0
at Receiver.controlMessage (/opt/iobroker/node_modules/ws/lib/receiver.js:561:18)
at Receiver.getData (/opt/iobroker/node_modules/ws/lib/receiver.js:429:42)
at Receiver.startLoop (/opt/iobroker/node_modules/ws/lib/receiver.js:148:22)
at Receiver._write (/opt/iobroker/node_modules/ws/lib/receiver.js:83:10)
at writeOrBuffer (node:internal/streams/writable:391:12)
at _write (node:internal/streams/writable:332:10)
at Receiver.Writable.write (node:internal/streams/writable:336:10)
at Socket.socketOnData (/opt/iobroker/node_modules/ws/lib/websocket.js:1272:35)
at Socket.emit (node:events:513:28)
at addChunk (node:internal/streams/readable:315:12)
at readableAddChunk (node:internal/streams/readable:289:9)
at Socket.Readable.push (node:internal/streams/readable:228:10)
at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
2022-12-25 10:52:06.717 - debug: innogy-smarthome.0 (1817) SOCKET CONNECTION TO THE INNOGY API WAS CLOSED
2022-12-25 10:52:07.284 - error: host.iobroker instance system.adapter.innogy-smarthome.0 terminated with code 6 (UNCAUGHT_EXCEPTION)


</body>
</html>

**Comment by Apollon77** [comment]
Ok, den Fehler kann ich abfangen. zum Rest muss ich bei Livisi nachfragen was man anders tun muss

**Comment by haahne** [comment]
Okay , und danke nochmal das du dich der Sache hier angenommen hast.

**Comment by Apollon77** [comment]
Aber eine Frage: SOnstige Steueraktionen gehen? Oder geht gerade keine mehr?

**Comment by Apollon77** [comment]
PS: CLoud oder Lokal? Falls Cloud mal lokal versucht?

**Comment by haahne** [comment]
Habe nur Heizkörperthermostate und Raumthermostate daher kann ich nur für diese sprechen. Sonst gehen alle Sachen wie Temps setzen usw. 
Hab es Lokal mit der SHC2 versucht.

**Comment by Apollon77** [comment]
Ok, mal schsauen was der Livisi Support sagt. Auch die Fehlermeldung ist jetzt eine andere

**Comment by Apollon77** [comment]
@haahne Weil es in deinem Log fehlt: Du hast abert schon die neuen Objekte versucht zu steuern? Da müsste noch LOgging zu changed state oder so von vor der Fehlermeldung sein

**Comment by haahne** [comment]
@Apollon77 Es steht als Überschrift oben im Post, weiß nicht warum er es fett markiert hat :D

2022-12-25 10:52:06.641 - debug: innogy-smarthome.0 (1817) Setting capability b716e897306b41f4b433ab60041f5563/WindowReductionActive to true 

oder meintest du etwas anderes?

**Comment by Apollon77** [comment]
Da sollte noch eine Zeile davor sein mit was mit "state changed" drin

**Comment by haahne** [comment]
<html>
<body>


innogy-smarthome.0 | 2022-12-26 14:35:09.969 | debug | SOCKET CONNECTION TO THE INNOGY API WAS CLOSED
innogy-smarthome.0 | 2022-12-26 14:35:09.965 | debug | STACK: RangeError: Invalid WebSocket frame: invalid status code 0 at Receiver.controlMessage (/opt/iobroker/node_modules/ws/lib/receiver.js:561:18) at Receiver.getData (/opt/iobroker/node_modules/ws/lib/receiver.js:429:42) at Receiver.startLoop (/opt/iobroker/node_modules/ws/lib/receiver.js:148:22) at Receiver._write (/opt/iobroker/node_modules/ws/lib/receiver.js:83:10) at writeOrBuffer (node:internal/streams/writable:391:12) at _write (node:internal/streams/writable:332:10) at Receiver.Writable.write (node:internal/streams/writable:336:10) at Socket.socketOnData (/opt/iobroker/node_modules/ws/lib/websocket.js:1272:35) at Socket.emit (node:events:513:28) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:289:9) at Socket.Readable.push (node:internal/streams/readable:228:10) at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
innogy-smarthome.0 | 2022-12-26 14:35:09.965 | debug | GOT AN IGNORED ERROR: {"code":"WS_ERR_INVALID_CLOSE_CODE"}
innogy-smarthome.0 | 2022-12-26 14:35:09.962 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
innogy-smarthome.0 | 2022-12-26 14:35:09.961 | info | terminating
innogy-smarthome.0 | 2022-12-26 14:35:09.960 | info | cleaned everything up...
innogy-smarthome.0 | 2022-12-26 14:35:09.959 | debug | SOCKET CONNECTION TO THE INNOGY API WAS CLOSED
innogy-smarthome.0 | 2022-12-26 14:35:09.955 | error | 400 - {"errorcode":1005,"description":"Missing argument or wrong value","messages":["Parameter [ windowReductionActive ] does not exist. Err: [ parameter [windowReductionActive] not found in action [SetState] ]"]}
innogy-smarthome.0 | 2022-12-26 14:35:09.955 | error | StatusCodeError: 400 - {"errorcode":1005,"description":"Missing argument or wrong value","messages":["Parameter [ windowReductionActive ] does not exist. Err: [ parameter [windowReductionActive] not found in action [SetState] ]"]} at new StatusCodeError (/opt/iobroker/node_modules/request-promise-core/lib/errors.js:32:15) at Request.plumbing.callback (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:104:33) at Request.RP$callback [as _callback] (/opt/iobroker/node_modules/request-promise-core/lib/plumbing.js:46:31) at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22) at Request.emit (node:events:513:28) at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1154:10) at Request.emit (node:events:513:28) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1076:12) at Object.onceWrapper (node:events:627:28) at IncomingMessage.emit (node:events:525:35) at endReadableNT (node:internal/streams/readable:1358:12) at processTicksAndRejections (node:internal/process/task_queues:83:21)
innogy-smarthome.0 | 2022-12-26 14:35:09.955 | error | unhandled promise rejection: 400 - {"errorcode":1005,"description":"Missing argument or wrong value","messages":["Parameter [ windowReductionActive ] does not exist. Err: [ parameter [windowReductionActive] not found in action [SetState] ]"]}
innogy-smarthome.0 | 2022-12-26 14:35:09.954 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
innogy-smarthome.0 | 2022-12-26 14:35:09.590 | debug | Setting capability b716e897306b41f4b433ab60041f5563/WindowReductionActive to true
innogy-smarthome.0 | 2022-12-26 14:35:09.586 | debug | state innogy-smarthome.0.Schlafzimmer.Heizkörperthermostat.Target-Temperature.WindowReductionActive changed: true (ack = false)


</body>
</html>

**Comment by Apollon77** [comment]
>  innogy-smarthome.0 | 2022-12-26 14:35:09.586 | debug | state innogy-smarthome.0.Schlafzimmer.Heizkörperthermostat.Target-Temperature.WindowReductionActive changed: true (ack = false)

This one was missing, looks good

**Comment by Apollon77** [comment]
@haahne Duuuuuuuuu ... Hast Du auch ein *.SetPoint.WindowReductionActive in dem gerät?Laut Livisi ist dieser State nur bei "setPoint" steuerbar .... KannST du bitte mal checken und schauen?

Bzw sage bitte auch welche shc generation genutzt wird
